[package]
name = "maskura-policy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
maskura-error = { path = "../error" }
ciborium.workspace = true
ed25519-dalek.workspace = true
serde.workspace = true
hex.workspace = true
uuid.workspace = true
rand.workspace = true
