# coding: utf-8

"""
    Maskura Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.7.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from maskura_client.models.backend_type import BackendType
from typing import Optional, Set
from typing_extensions import Self

class BackendConfigRequest(BaseModel):
    """
    Dashboard request DTO. Secrets are accepted only on writes and are never reused as a response type. JSON uses `backend_type`: `managed` needs no other fields; `s3_compatible` needs `endpoint`, `access_key`, `secret_key`, and `region`.
    """ # noqa: E501
    access_key: Optional[StrictStr] = None
    backend_type: BackendType
    endpoint: Optional[StrictStr] = None
    external_id: Optional[StrictStr] = None
    region: Optional[StrictStr] = None
    role_arn: Optional[StrictStr] = None
    secret_key: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["access_key", "backend_type", "endpoint", "external_id", "region", "role_arn", "secret_key"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BackendConfigRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if external_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_id is None and "external_id" in self.model_fields_set:
            _dict['external_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BackendConfigRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "access_key": obj.get("access_key"),
            "backend_type": obj.get("backend_type"),
            "endpoint": obj.get("endpoint"),
            "external_id": obj.get("external_id"),
            "region": obj.get("region"),
            "role_arn": obj.get("role_arn"),
            "secret_key": obj.get("secret_key")
        })
        return _obj


