# coding: utf-8

"""
    Maskura Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.7.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BackendType(str, Enum):
    """
    BackendType
    """

    """
    allowed enum values
    """
    S3_COMPATIBLE = 's3_compatible'
    AWS_ROLE = 'aws_role'
    MANAGED = 'managed'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BackendType from a JSON string"""
        return cls(json.loads(json_str))


