# coding: utf-8

"""
    Maskura Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from maskura_client.models.backend_type import BackendType
from typing import Optional, Set
from typing_extensions import Self

class BackendConfigResponse(BaseModel):
    """
    Redacted dashboard representation. Credential material is intentionally absent from this type, so a GET cannot serialize it by mistake. Its exact JSON keys are `configured`, `backend_type`, `endpoint`, `region`, `role_arn`, `external_id`, `access_key_configured`, and `secret_key_configured`. `external_id` is not a secret: it is the confused-deputy-prevention correlation value an operator pastes into the role trust policy.
    """ # noqa: E501
    access_key_configured: StrictBool
    backend_type: Optional[BackendType] = None
    configured: StrictBool
    endpoint: Optional[StrictStr] = None
    external_id: Optional[StrictStr] = None
    region: Optional[StrictStr] = None
    role_arn: Optional[StrictStr] = None
    secret_key_configured: StrictBool
    __properties: ClassVar[List[str]] = ["access_key_configured", "backend_type", "configured", "endpoint", "external_id", "region", "role_arn", "secret_key_configured"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BackendConfigResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if backend_type (nullable) is None
        # and model_fields_set contains the field
        if self.backend_type is None and "backend_type" in self.model_fields_set:
            _dict['backend_type'] = None

        # set to None if endpoint (nullable) is None
        # and model_fields_set contains the field
        if self.endpoint is None and "endpoint" in self.model_fields_set:
            _dict['endpoint'] = None

        # set to None if external_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_id is None and "external_id" in self.model_fields_set:
            _dict['external_id'] = None

        # set to None if region (nullable) is None
        # and model_fields_set contains the field
        if self.region is None and "region" in self.model_fields_set:
            _dict['region'] = None

        # set to None if role_arn (nullable) is None
        # and model_fields_set contains the field
        if self.role_arn is None and "role_arn" in self.model_fields_set:
            _dict['role_arn'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BackendConfigResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "access_key_configured": obj.get("access_key_configured"),
            "backend_type": obj.get("backend_type"),
            "configured": obj.get("configured"),
            "endpoint": obj.get("endpoint"),
            "external_id": obj.get("external_id"),
            "region": obj.get("region"),
            "role_arn": obj.get("role_arn"),
            "secret_key_configured": obj.get("secret_key_configured")
        })
        return _obj


