# coding: utf-8

"""
    Maskura Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maskura_client.models.backend_config_request import BackendConfigRequest

class TestBackendConfigRequest(unittest.TestCase):
    """BackendConfigRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BackendConfigRequest:
        """Test BackendConfigRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BackendConfigRequest`
        """
        model = BackendConfigRequest()
        if include_optional:
            return BackendConfigRequest(
                access_key = '',
                backend_type = 's3_compatible',
                endpoint = '',
                external_id = '',
                region = '',
                role_arn = '',
                secret_key = ''
            )
        else:
            return BackendConfigRequest(
                backend_type = 's3_compatible',
        )
        """

    def testBackendConfigRequest(self):
        """Test BackendConfigRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
