# coding: utf-8

"""
    Maskura Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from s4_client.models.mcp_token_response import McpTokenResponse

class TestMcpTokenResponse(unittest.TestCase):
    """McpTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> McpTokenResponse:
        """Test McpTokenResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `McpTokenResponse`
        """
        model = McpTokenResponse()
        if include_optional:
            return McpTokenResponse(
                created_at = '',
                credential_id = '',
                expires_at = '',
                label = '',
                token_hash = '',
                workspace_id = ''
            )
        else:
            return McpTokenResponse(
                created_at = '',
                credential_id = '',
                label = '',
                token_hash = '',
        )
        """

    def testMcpTokenResponse(self):
        """Test McpTokenResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
