# coding: utf-8

"""
    Maskura Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from s4_client.models.delete_key_request import DeleteKeyRequest

class TestDeleteKeyRequest(unittest.TestCase):
    """DeleteKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteKeyRequest:
        """Test DeleteKeyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteKeyRequest`
        """
        model = DeleteKeyRequest()
        if include_optional:
            return DeleteKeyRequest(
                key_id = ''
            )
        else:
            return DeleteKeyRequest(
                key_id = '',
        )
        """

    def testDeleteKeyRequest(self):
        """Test DeleteKeyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
