# coding: utf-8

"""
    Maskura Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from s4_client.api.mcp_api import McpApi


class TestMcpApi(unittest.TestCase):
    """McpApi unit test stubs"""

    def setUp(self) -> None:
        self.api = McpApi()

    def tearDown(self) -> None:
        pass

    def test_create_mcp_token(self) -> None:
        """Test case for create_mcp_token

        Create an MCP bearer token (`s4m_...`). The plaintext token is returned once and only its hash is stored.
        """
        pass

    def test_delete_mcp_token(self) -> None:
        """Test case for delete_mcp_token

        Revoke an MCP bearer token.
        """
        pass

    def test_get_mcp_tokens(self) -> None:
        """Test case for get_mcp_tokens

        List MCP bearer tokens for the authenticated user (hashes only).
        """
        pass


if __name__ == '__main__':
    unittest.main()
