# coding: utf-8

"""
    Maskura Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from s4_client.models.list_key_response import ListKeyResponse

class TestListKeyResponse(unittest.TestCase):
    """ListKeyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListKeyResponse:
        """Test ListKeyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListKeyResponse`
        """
        model = ListKeyResponse()
        if include_optional:
            return ListKeyResponse(
                created_at = '',
                expires_at = '',
                key_id = '',
                label = '',
                public_key_pem = '',
                workspace_id = ''
            )
        else:
            return ListKeyResponse(
                created_at = '',
                key_id = '',
                label = '',
        )
        """

    def testListKeyResponse(self):
        """Test ListKeyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
