# coding: utf-8

"""
    Maskura Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from s4_client.models.backend_type import BackendType

class TestBackendType(unittest.TestCase):
    """BackendType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBackendType(self):
        """Test BackendType"""
        # inst = BackendType()

if __name__ == '__main__':
    unittest.main()
