# coding: utf-8

"""
    Maskura Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from s4_client.models.backend_config_response import BackendConfigResponse

class TestBackendConfigResponse(unittest.TestCase):
    """BackendConfigResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BackendConfigResponse:
        """Test BackendConfigResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BackendConfigResponse`
        """
        model = BackendConfigResponse()
        if include_optional:
            return BackendConfigResponse(
                access_key_configured = True,
                backend_type = 's3_compatible',
                configured = True,
                endpoint = '',
                external_id = '',
                region = '',
                role_arn = '',
                secret_key_configured = True
            )
        else:
            return BackendConfigResponse(
                access_key_configured = True,
                configured = True,
                secret_key_configured = True,
        )
        """

    def testBackendConfigResponse(self):
        """Test BackendConfigResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
