# coding: utf-8

"""
    Maskura Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from s4_client.api.backend_api import BackendApi


class TestBackendApi(unittest.TestCase):
    """BackendApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BackendApi()

    def tearDown(self) -> None:
        pass

    def test_get_backend(self) -> None:
        """Test case for get_backend

        """
        pass

    def test_put_backend(self) -> None:
        """Test case for put_backend

        """
        pass


if __name__ == '__main__':
    unittest.main()
