# coding: utf-8

"""
    Maskura Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.7.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maskura_client.api.keys_api import KeysApi


class TestKeysApi(unittest.TestCase):
    """KeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KeysApi()

    def tearDown(self) -> None:
        pass

    def test_create_key(self) -> None:
        """Test case for create_key

        Create a new API key
        """
        pass

    def test_delete_key(self) -> None:
        """Test case for delete_key

        Revoke an API key
        """
        pass

    def test_get_keys(self) -> None:
        """Test case for get_keys

        List API keys for the authenticated user
        """
        pass


if __name__ == '__main__':
    unittest.main()
