# coding: utf-8

"""
    Maskura Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from s4_client.models.object_response import ObjectResponse

class TestObjectResponse(unittest.TestCase):
    """ObjectResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ObjectResponse:
        """Test ObjectResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ObjectResponse`
        """
        model = ObjectResponse()
        if include_optional:
            return ObjectResponse(
                key = '',
                size = 0
            )
        else:
            return ObjectResponse(
                key = '',
                size = 0,
        )
        """

    def testObjectResponse(self):
        """Test ObjectResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
