# coding: utf-8

"""
    Maskura Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maskura_client.api.objects_api import ObjectsApi


class TestObjectsApi(unittest.TestCase):
    """ObjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ObjectsApi()

    def tearDown(self) -> None:
        pass

    def test_list_objects(self) -> None:
        """Test case for list_objects

        List all objects in the store
        """
        pass


if __name__ == '__main__':
    unittest.main()
