# coding: utf-8

"""
    Maskura Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from s4_client.models.create_key_request import CreateKeyRequest

class TestCreateKeyRequest(unittest.TestCase):
    """CreateKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateKeyRequest:
        """Test CreateKeyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateKeyRequest`
        """
        model = CreateKeyRequest()
        if include_optional:
            return CreateKeyRequest(
                expires_in = 0,
                label = '',
                public_key_pem = ''
            )
        else:
            return CreateKeyRequest(
                label = '',
        )
        """

    def testCreateKeyRequest(self):
        """Test CreateKeyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
