# coding: utf-8

# flake8: noqa

"""
    Maskura Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "BackendApi",
    "KeysApi",
    "McpApi",
    "ObjectsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ApiKeyResponse",
    "BackendConfigRequest",
    "BackendConfigResponse",
    "BackendType",
    "CreateKeyRequest",
    "CreateMcpTokenRequest",
    "DeleteKeyRequest",
    "DeleteMcpTokenRequest",
    "ListKeyResponse",
    "McpTokenCreatedResponse",
    "McpTokenResponse",
    "ObjectResponse",
]

# import apis into sdk package
from s4_client.api.backend_api import BackendApi as BackendApi
from s4_client.api.keys_api import KeysApi as KeysApi
from s4_client.api.mcp_api import McpApi as McpApi
from s4_client.api.objects_api import ObjectsApi as ObjectsApi

# import ApiClient
from s4_client.api_response import ApiResponse as ApiResponse
from s4_client.api_client import ApiClient as ApiClient
from s4_client.configuration import Configuration as Configuration
from s4_client.exceptions import OpenApiException as OpenApiException
from s4_client.exceptions import ApiTypeError as ApiTypeError
from s4_client.exceptions import ApiValueError as ApiValueError
from s4_client.exceptions import ApiKeyError as ApiKeyError
from s4_client.exceptions import ApiAttributeError as ApiAttributeError
from s4_client.exceptions import ApiException as ApiException

# import models into sdk package
from s4_client.models.api_key_response import ApiKeyResponse as ApiKeyResponse
from s4_client.models.backend_config_request import BackendConfigRequest as BackendConfigRequest
from s4_client.models.backend_config_response import BackendConfigResponse as BackendConfigResponse
from s4_client.models.backend_type import BackendType as BackendType
from s4_client.models.create_key_request import CreateKeyRequest as CreateKeyRequest
from s4_client.models.create_mcp_token_request import CreateMcpTokenRequest as CreateMcpTokenRequest
from s4_client.models.delete_key_request import DeleteKeyRequest as DeleteKeyRequest
from s4_client.models.delete_mcp_token_request import DeleteMcpTokenRequest as DeleteMcpTokenRequest
from s4_client.models.list_key_response import ListKeyResponse as ListKeyResponse
from s4_client.models.mcp_token_created_response import McpTokenCreatedResponse as McpTokenCreatedResponse
from s4_client.models.mcp_token_response import McpTokenResponse as McpTokenResponse
from s4_client.models.object_response import ObjectResponse as ObjectResponse

# High-level canonical and compatibility exports maintained by the Maskura overlay.
from s4_client.highlevel import MaskuraClient as MaskuraClient
from s4_client.highlevel import S4Client as S4Client
__all__.extend(["MaskuraClient", "S4Client"])
