/**
 * Maskura Gateway API
 * Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BackendType } from '../models/BackendType';
import { HttpFile } from '../http/http';

/**
* Dashboard request DTO. Secrets are accepted only on writes and are never reused as a response type. JSON uses `backend_type`: `managed` needs no other fields; `s3_compatible` needs `endpoint`, `access_key`, `secret_key`, and `region`.
*/
export class BackendConfigRequest {
    'accessKey'?: string;
    'backendType': BackendType;
    'endpoint'?: string;
    'externalId'?: string | null;
    'region'?: string;
    'roleArn'?: string;
    'secretKey'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessKey",
            "baseName": "access_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "backendType",
            "baseName": "backend_type",
            "type": "BackendType",
            "format": ""
        },
        {
            "name": "endpoint",
            "baseName": "endpoint",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string",
            "format": ""
        },
        {
            "name": "roleArn",
            "baseName": "role_arn",
            "type": "string",
            "format": ""
        },
        {
            "name": "secretKey",
            "baseName": "secret_key",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BackendConfigRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


