/**
 * Maskura Gateway API
 * Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.
 *
 * OpenAPI spec version: 0.5.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BackendType } from '../models/BackendType';
import { HttpFile } from '../http/http';

/**
* Redacted dashboard representation. Credential material is intentionally absent from this type, so a GET cannot serialize it by mistake. Its exact JSON keys are `configured`, `backend_type`, `endpoint`, `region`, `role_arn`, `external_id`, `access_key_configured`, and `secret_key_configured`. `external_id` is not a secret: it is the confused-deputy-prevention correlation value an operator pastes into the role trust policy.
*/
export class BackendConfigResponse {
    'accessKeyConfigured': boolean;
    'backendType'?: BackendType | null;
    'configured': boolean;
    'endpoint'?: string | null;
    'externalId'?: string | null;
    'region'?: string | null;
    'roleArn'?: string | null;
    'secretKeyConfigured': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessKeyConfigured",
            "baseName": "access_key_configured",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "backendType",
            "baseName": "backend_type",
            "type": "BackendType",
            "format": ""
        },
        {
            "name": "configured",
            "baseName": "configured",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "endpoint",
            "baseName": "endpoint",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string",
            "format": ""
        },
        {
            "name": "roleArn",
            "baseName": "role_arn",
            "type": "string",
            "format": ""
        },
        {
            "name": "secretKeyConfigured",
            "baseName": "secret_key_configured",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BackendConfigResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


